curriculum/urls.py
from django.urls import path
from . import views

app_name='curriculum'
urlpatterns = [
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(),name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(),name='lesson_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpdateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessonDeleteView.as_view(),name='lesson_delete'),

]

elearn/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
]






# app_name = 'app_users'
# urlpatterns = [
#     path('',views.HomeView.as_view(),name='index'),
        # path('contact/', views.ContactView.as_view(), name="contact"),
# ]
# HomeView.as_view()

elearning/urls.py
from django.contrib import admin
from django.urls import path
import elearn
import curriculum
# import elearn import views
# from elearning.urls import elearn
from django.conf.urls import include

urlpatterns = [
    path('', include('elearn.urls')),
    path('curriculum/',include('curriculum.urls')),
    path('admin/', admin.site.urls),    
]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

curriculum/models.py
from django.db import models

# # Create your models here.
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.contrib.auth.models import User
import os

# Create your models here.
class Standard(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(null=True, blank=True)
    description = models.TextField(max_length=500,blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

def save_subject_image(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.subject_id:
        filename = 'Subject_Pictures/{}.{}'.format(instance.subject_id, ext)
    return os.path.join(upload_to, filename)

class Subject(models.Model):
    subject_id = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE, related_name='subjects')
    image = models.ImageField(upload_to=save_subject_image, blank=True, verbose_name='Subject Image')
    description = models.TextField(max_length=500,blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.subject_id)
        super().save(*args, **kwargs)


def save_lesson_files(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.lesson_id:
        filename = 'lesson_files/{}/{}.{}'.format(instance.lesson_id,instance.lesson_id, ext)
        if os.path.exists(filename):
            new_name = str(instance.lesson_id) + str('1')
            filename =  'lesson_images/{}/{}.{}'.format(instance.lesson_id,new_name, ext)
    return os.path.join(upload_to, filename)

class Lesson(models.Model):
    lesson_id = models.CharField(max_length=100, unique=True)
    Standard = models.ForeignKey(Standard, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE,related_name='lessons')
    name = models.CharField(max_length=250)
    position = models.PositiveSmallIntegerField(verbose_name="Chapter no.")
    slug = models.SlugField(null=True, blank=True)
    video = models.FileField(upload_to=save_lesson_files,verbose_name="Video", blank=True, null=True)
    ppt = models.FileField(upload_to=save_lesson_files,verbose_name="Presentations", blank=True)
    Notes = models.FileField(upload_to=save_lesson_files,verbose_name="Notes", blank=True)

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('curriculum:lesson_list', kwargs={'slug':self.subject.slug, 'standard':self.Standard.slug})

# class WorkingDays(models.Model):
#     standard = models.ForeignKey(Standard, on_delete=models.CASCADE,related_name='standard_days')
#     day = models.CharField(max_length=100)
#     def __str__(self):
#         return self.day

# class TimeSlots(models.Model):
#     standard = models.ForeignKey(Standard, on_delete=models.CASCADE,related_name='standard_time_slots')
#     start_time = models.TimeField()
#     end_time = models.TimeField()

#     def __str__(self):
#         return str(self.start_time) + ' - ' + str(self.end_time) 

# class SlotSubject(models.Model):
#     standard = models.ForeignKey(Standard, on_delete=models.CASCADE,related_name='standard_slots')
#     day = models.ForeignKey(WorkingDays, on_delete=models.CASCADE,related_name='standard_slots_days')
#     slot = models.ForeignKey(TimeSlots, on_delete=models.CASCADE,related_name='standard_slots_time')
#     slot_subject = models.ForeignKey(Subject, on_delete=models.CASCADE,related_name='standard_slots_subject')

#     def __str__(self):
#         return str(self.standard)+ ' - ' + str(self.day) + ' - ' + str(self.slot) + ' - ' + str(self.slot_subject)

class Comment(models.Model):
    lesson_name = models.ForeignKey(Lesson,null=True, on_delete=models.CASCADE,related_name='comments')
    comm_name = models.CharField(max_length=100, blank=True)
    # reply = models.ForeignKey("Comment", null=True, blank=True, on_delete=models.CASCADE,related_name='replies')
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    body = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.comm_name = slugify("comment by" + "-" + str(self.author) + str(self.date_added))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.comm_name

    class Meta:
        ordering = ['-date_added']

class Reply(models.Model):
    comment_name = models.ForeignKey(Comment, on_delete=models.CASCADE,related_name='replies')
    reply_body = models.TextField(max_length=500)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "reply to " + str(self.comment_name.comm_name)

curriculum/forms.py
from django import forms
from .models import Comment, Reply,Lesson
# Comment, Reply, 
class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ('lesson_id','name','position','video','ppt','Notes')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        labels = {"body":"Comment:"}

        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control', 'rows':4, 'cols':70, 'placeholder':"Enter Your Comment"}),
        }

    # def __init__(self, *args, **kwargs):
    #     self.request = kwargs.pop('request', None)
    #     super(CommentForm, self).__init__(*args, **kwargs)   


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('reply_body',)

        widgets = {
            'reply_body': forms.Textarea(attrs={'class':'form-control', 'rows':2, 'cols':10}),
        }

    # def __init__(self, *args, **kwargs):
    #     self.request = kwargs.pop('request', None)
    #     super(ReplyForm, self).__init__(*args, **kwargs)

curriculum/views.py
from django.shortcuts import render

# # Create your views here.

from django.views.generic import (TemplateView, DetailView,
                                     ListView, CreateView,
                                     UpdateView,DeleteView,FormView,)
from .models import Standard, Subject, Lesson
# , Comment, WorkingDays, TimeSlots
from django.urls import reverse_lazy
from .forms import CommentForm,ReplyForm,LessonForm
from django.http import HttpResponseRedirect
# CommentForm,ReplyForm, 


class StandardListView(ListView):
     context_object_name = 'standards'
     model = Standard
     template_name = 'curriculum/standard_list_view.html'

class SubjectListView(DetailView):
    context_object_name = 'standards'
    # extra_context = {
    #     'slots': TimeSlots.objects.all()
    # }
    model = Standard
    template_name = 'curriculum/subject_list_view.html'

class LessonListView(DetailView):
    context_object_name = 'subjects'
    model = Subject
    template_name = 'curriculum/lesson_list_view.html'

class LessonDetailView(DetailView, FormView):
    context_object_name = 'lessons'
    model = Lesson
    template_name = 'curriculum/lesson_detail_view.html'
    form_class = CommentForm
    second_form_class = ReplyForm

# ...
# send two forms to page
# see which one is posted
# take action accordingly
# ...


    def get_context_data(self, **kwargs):
        context = super(LessonDetailView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class()
        # context['comments'] = Comment.objects.filter(id=self.object.id)
        # request=self.request
        return context


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.get_form_class()
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'

        form = self.get_form(form_class)
        # print("the form name is : ", form)
        # print("form name: ", form_name)
        # print("form_class:",form_class)

        if form_name=='form' and form.is_valid():
            print("comment form is returned")
            return self.form_valid(form)
        elif form_name=='form2' and form.is_valid():
            print("reply form is returned")
            return self.form2_valid(form)


    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.Standard
        subject = self.object.subject
        return reverse_lazy('curriculum:lesson_detail',kwargs={'standard':standard.slug,
                                                             'subject':subject.slug,
                                                             'slug':self.object.slug})

    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.lesson_name = self.object.comments.name
        fm.lesson_name_id = self.object.id
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

    def form2_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.comment_name_id = self.request.POST.get('comment.id')
        fm.save()
        return HttpResponseRedirect(self.get_success_url())


class LessonCreateView(CreateView):
    # fields = ('lesson_id','name','position','image','video','ppt','Notes')
    form_class = LessonForm
    context_object_name = 'subject'
    model= Subject
    template_name = 'curriculum/lesson_create.html'

    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.standard
        return reverse_lazy('curriculum:lesson_list',kwargs={'standard':standard.slug,
                                                             'slug':self.object.slug})


    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.created_by = self.request.user
        fm.Standard = self.object.standard
        fm.subject = self.object
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

class LessonUpdateView(UpdateView):
    fields = ('name','position','video','ppt','Notes')
    model= Lesson
    template_name = 'curriculum/lesson_update.html'
    context_object_name = 'lessons'

class LessonDeleteView(DeleteView):
    model= Lesson
    context_object_name = 'lessons'
    template_name = 'curriculum/lesson_delete.html'

    def get_success_url(self):
        print(self.object)
        standard = self.object.Standard
        subject = self.object.subject
        return reverse_lazy('curriculum:lesson_list',kwargs={'standard':standard.slug,'slug':subject.slug})

curriculum/templates/curriculum/lesson_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<form method="Post">

  {% csrf_token %}
  {{form|crispy}}
  <input type="submit" name="submit" value="submit">

</form>



{% endblock %}

curriculum/templates/curriculum/lesson_delete.html
{% extends 'base.html' %}

{% block content %}
<h3>Are you sure you want to delete?</h3>
<form method="Post">

  {% csrf_token %}
 

  
  <input type="submit" name="" value="Delete">
  <a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}"></a>

  
  <a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">Cancel delete</a>
  

</form>


{% endblock %}

curriculum/templates/curriculum/lesson_detail_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<p>Created on {{lessons.created_at}} by {{lessons.created_by}}</p><br>
<a href="{% url 'curriculum:lesson_update' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">Update Lesson</a>

<a href="{% url 'curriculum:lesson_delete' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">Delete Lesson</a>


<h4>Post your comment or questions below</h4>
<form method="post">
  <div class="form-group">
    {%csrf_token%}
    {{form|crispy}}
    <input type="submit" name="form" value="Add Comment" class="btn btn-primary btn-sm">
  </div>
</form>

{% for comment in lessons.comments.all %}
<h4>{{comment.author}} <small><i>Posted on {{comment.date_added}}</i></small></h4>
<p>{{comment.body}}</p>
    {% for reply in comment.replies.all %}
      <h5>{{reply.author}} <small><i>Posted on {{reply.date_added}}</i></small></h5>
      <p>{{reply.reply_body}}</p>
    {% endfor %}

    <form method="post">
      <input type="hidden" name="comment.id" value="{{comment.id}}">
      <input type="hidden" name="comment.comm_name" value="{{comment.comm_name}}">
      {% csrf_token %%}
      {{form2|crispy}}
      <input type="submit" name="form2" value="Add Reply" class="btn btn-primary btn-sm">
    </form>
  {% endfor %}

{% endblock %}

curriculum/templates/curriculum/lesson_list_view.html
{% extends 'base.html' %}

{% block content %}

{% for lesson in subjects.lessons.all %}

<a href="{% url 'curriculum:lesson_detail' slug=lesson.slug subject=subjects.slug standard=lesson.Standard.slug %}">Chapter - {{lesson.position}}: {{lesson.name}}</a><br>

{% endfor %}

<a href="{% url 'curriculum:lesson_create' standard=subjects.standard.slug slug=subjects.slug %}">Create Lesson</a>

{% endblock %}

{% comment %} {{subject.name}} {% endcomment %}

curriculum/templates/curriculum/lesson_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<form method="Post">

  {% csrf_token %}
  {{form|crispy}}
  <input type="submit" name="submit" value="submit">
  <a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">Cancel Update</a>

  

</form>


{% endblock %}

curriculum/templates/curriculum/standard_list_view.html
{% extends 'base.html' %}

{% block content %}
{% for standard in standards %}

    <a href="{% url 'curriculum:subject_list' slug=standard.slug %}">{{standard.name}}</a><br>

{% endfor %}

{% endblock %}

curriculum/templates/curriculum/subject_list_view.html
{% extends 'base.html' %}

{% block content %}

{% for subject in standards.subjects.all %}

          <a href="{% url 'curriculum:lesson_list' slug=subject.slug standard=standards.slug %}">{{subject.name}}</a><br>
          <p>{{subject.description|truncatechars:75}}</p><br><br>

{% endfor %}

{% endblock %}