curriculum/urls.py
from django.urls import path
from . import views

app_name='curriculum'
urlpatterns = [
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(),name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(),name='lesson_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpdateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessonDeleteView.as_view(),name='lesson_delete'),

]

elearn/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
]






# app_name = 'app_users'
# urlpatterns = [
#     path('',views.HomeView.as_view(),name='index'),
        # path('contact/', views.ContactView.as_view(), name="contact"),
# ]
# HomeView.as_view()

elearning/urls.py
from django.contrib import admin
from django.urls import path
import elearn
import curriculum
# import elearn import views
# from elearning.urls import elearn
from django.conf.urls import include

urlpatterns = [
    path('', include('elearn.urls')),
    path('curriculum/',include('curriculum.urls')),
    path('admin/', admin.site.urls),    
]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/master_css.css' %}">
    <title>eKlass LMS</title>
  </head>
  <body>
<body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
      <div class="container">
        <a href="#" class="navbar-brand">eKlass</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navmenu">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navmenu">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a href="{% url 'index' %}" class="nav-link">Home</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'curriculum:standard_list' %}" class="nav-link">Courses</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'register' %}" class="nav-link">Register</a>
            </li>
            {% if user.is_authenticated %}
             <li class="nav-item">
              <a href="{% url 'user_logout' %}" class="nav-link">Logout</a>
            </li>
             {% else %}
             <li class="nav-item">
              <a href="{% url 'user_login' %}" class="nav-link">Login</a>
            </li>
             {% endif %}
             {% if user.is_superuser %}
             <li class="nav-item">
              <a href="{% url 'admin:index' %}" class="nav-link">Admin</a>
            </li>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <!-- Showcase -->
    <section
      class="bg-dark text-light p-5 p-lg-0 pt-lg-4 text-center text-sm-start">
      <div class="container">
        <div class="d-sm-flex align-items-center justify-content-between">
          <div>
            <p class="lead my-4">
              <p class="lead my-4">
            <h2>Welcome to eklass<span class="text-warning"> your e-Learning classroom</span></h2>
            <p class="lead my-4">
              We focus on providing a learning platform for teaching students their schools curriculum courses online 
            </p>
            <a href="{% url 'curriculum:standard_list' %}"> 
            <button
              class="btn btn-primary btn-lg"
              data-bs-toggle="modal"
              {% comment %} data-bs-target="#enroll" {% endcomment %}
            >
            Start Learning
            </button></a>
          </div>
    
          <img
            class="img-fluid w-50 d-none d-sm-block"  
            src="https://thumbs.dreamstime.com/z/book-open-lying-table-sheets-spread-out-like-fan-blue-background-large-thick-hardcover-light-wood-pages-fanned-184016738.jpg"
            alt=""
          />
        </div>
      </div>
    </section>


<section>
   <div class="container">
        {% block content %}
        
        
        {% endblock %}
   </div>
</section>
<!-- Footer -->
    {% comment %} <footer >
      <div class="container">
        

        <a href="#" class="position-absolute bottom-0 end-0 p-5">
          <i class="bi bi-arrow-up-circle h1"></i>
        </a>
      </div>
    </footer> {% endcomment %}



<footer class="p-5 bg-dark text-white text-center position-relative font-size">
  <div class="container">
    <div class="row mt-4">

      <div class="col-md-4 mt-4">
        <h6>About Us</h6>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed feugiat lorem porttitor ex fringilla, vel viverra lectus mollis. Vivamus sit amet sem mauris. Aenean convallis justo ac nunc lobortis ornare. Aenean a leo odio. Aenean condimentum.
        </div>

        <div class="col-md-4 mt-4">
          <h6>Some Useful Info</h6>
          <ul>
            <li>Item 1</li>
            <li>Item 2</li>
            <li>Item 3</li>
            <li>Item 4</li>
          </ul>
        </div>

        <div class="col-md-4 mt-4">
          <h6>Contact Us</h6>
          <ul>
            <li>Address: 1701 Towne Crossing Blvd, Mansfield, Tx </li>
            <li>Email: tandemtechnik@gmail.com</li>
            <li>Tel: +1 (682) 366 4524</li>
          </ul>
        </div>
      </div>

      <div class="footer-copyright text-center py-3">
        <p class="lead"><small>Copyright &copy; 2021 Tandemtechnik</small></p>
      </div>

    </div>
  </div>

      

  <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
      crossorigin="anonymous"
    ></script>   
  </body>
</html>